package net.sf.laja.cdd.state.mouth;

import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class MouthBehaviour implements MouthStateComparable {
    protected final MouthState state;
    protected MouthStateBuilder stateBuilder;

    public MouthBehaviour(MouthState state) {
        this.state = state;
        state.setEncapsulator(this);
    }

    public MouthBehaviour(MouthState state, MouthStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
        state.setEncapsulator(this);
    }

    public MouthState getState(Certificate certificate) {
        if (certificate == null) {
            throw new IllegalArgumentException("Certificate can not be null!");
        }
        return state;
    }
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof MouthStateComparable)) return false;
        return state.equals(obj);
    }

    @Override
    public int hashCode() {
        return state.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
