package net.sf.laja.cdd.behaviour.scaryeye;

import net.sf.laja.cdd.state.eye.*;

import net.sf.laja.cdd.behaviour.eye.Eye;
import net.sf.laja.cdd.behaviour.eye.EyeFactory;

import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public abstract class ScaryEyeAbstractList implements List<ScaryEye> {
    protected EyeStateList stateList;
    protected final List<ScaryEye> list = new ArrayList<ScaryEye>();

    public ScaryEyeAbstractList(ScaryEye... list) {
        this.list.addAll(Arrays.asList(list));
    }

    public ScaryEyeAbstractList(List<ScaryEye> list) {
        this.list.addAll(list);
    }

    public int size() {
        return list.size();
    }

    public boolean isEmpty() {
        return list.isEmpty();
    }

    public boolean contains(Object element) {
        return list.contains(element);
    }

    public Iterator<ScaryEye> iterator() {
        return list.iterator();
    }

    public Object[] toArray() {
        return list.toArray();
    }

    public <ScaryEye> ScaryEye[] toArray(ScaryEye[] array) {
        return list.toArray(array);
    }

    public boolean add(ScaryEye element) {
        if (stateList != null) {
            stateList.add(element.getState(stateList));
        }
        return list.add(element);
    }

    public void add(int index, ScaryEye element) {
        if (stateList != null) {
            stateList.add(index, element.getState(stateList));
        }
        list.add(index, element);
    }

    public boolean addAll(Collection<? extends ScaryEye> collection) {
        if (stateList != null) {
            List newElements = new ArrayList(collection.size());
            for (ScaryEye element : collection) {
                newElements.add(element.getState(stateList));
            }
            stateList.addAll(newElements);
        }
        return list.addAll(collection);
    }

    public boolean addAll(int index, Collection<? extends ScaryEye> collection) {
        if (stateList != null) {
            List newElements = new ArrayList(collection.size());
            for (ScaryEye element : collection) {
                newElements.add(element.getState(stateList));
            }
            stateList.addAll(index, newElements);
        }
        return list.addAll(index, collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof ScaryEye)) {
            return false;
        }
        if (stateList != null) {
            stateList.remove(((ScaryEye)element).getState(stateList));
        }
        return list.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return list.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        if (stateList != null) {
            List removedElements = new ArrayList(collection.size());
            List removedStateElements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof ScaryEye) {
                    removedElements.add(element);
                    removedStateElements.add(((ScaryEye)element).getState(stateList));
                }
            }
            stateList.removeAll(removedStateElements);
            return list.removeAll(removedElements);
        }
        return list.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        if (stateList != null) {
            List retainedElements = new ArrayList(collection.size());
            List retainedStateElements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof ScaryEye) {
                    retainedElements.add(element);
                    retainedStateElements.add(((ScaryEye)element).getState(stateList));
                }
            }
            stateList.retainAll(retainedStateElements);
            return list.retainAll(retainedElements);
        }
        return list.retainAll(collection);
    }

    public void clear() {
        if (stateList != null) {
            stateList.clear();
        }
        list.clear();
    }

    public ScaryEye get(int index) {
        return list.get(index);
    }

    public ScaryEye set(int index, ScaryEye element) {
        if (stateList != null) {
            stateList.set(index, element.getState(stateList));
        }
        return list.set(index, element);
    }

    public ScaryEye remove(int index) {
        if (stateList != null) {
            stateList.remove(index);
        }
        return list.remove(index);
    }

    public int indexOf(Object element) {
        return list.indexOf(element);
    }

    public int lastIndexOf(Object element) {
        return list.lastIndexOf(element);
    }

    public ListIterator<ScaryEye> listIterator() {
        return list.listIterator();
    }

    public ListIterator<ScaryEye> listIterator(int index) {
        return list.listIterator(index);
    }

    public List<ScaryEye> subList(int fromIndex, int toIndex) {
        return list.subList(fromIndex, toIndex);
    }

    @Override
    public boolean equals(Object o) {
        return list.equals(o);
    }

    @Override
    public int hashCode() {
        return list.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{list=" + list + '}';
    }
}
