package net.sf.laja.example.file.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface DirectoryBehaviourFactory {
    Object create(DirectoryState state, Object... args);
}
