package net.sf.laja.example.file.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface DirectoryStateBuilder {
    void withDirectoryPath(String directoryPath);
    boolean isValid();
    Object as(DirectoryBehaviourFactory factory, Object... args);
    DirectoryState getDirectoryState(net.sf.laja.example.file.state.Certificate certificate);
}
