package net.sf.laja.example.file.state;

import net.sf.laja.example.file.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface DirectoryStateBuilder {
    void withDirectoryPath(String directoryPath);
    boolean isValid();
    Object as(DirectoryStateBehaviourFactory factory, Object... args);
    DirectoryState getDirectoryState(net.sf.laja.example.file.state.Certificate certificate);
}
