package net.sf.laja.example.file.state;

import net.sf.laja.example.file.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface FileStateBuilder {
    void withFilename(String filename);
    boolean isValid();
    Object as(FileStateBehaviourFactory factory, Object... args);
    FileState getFileState(net.sf.laja.example.file.state.Certificate certificate);
}
