package net.sf.laja.example.file.state;

import net.sf.laja.example.file.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class FileStateImpl implements FileState {
    protected String filename;

    private boolean _encapsulated = false;
    private Object _encapsulator;

    FileStateImpl() {
    }

    public FileStateImpl(Certificate certificate) {
        this();
        if (certificate == null) {
            throw new IllegalArgumentException("Certificate can not be null");
        }
    }

    public static FileStateBuilder build() {
        return new FileStateBuilderImpl();
    }

    public static FileStateBuilder build(FileState state) {
        return new FileStateBuilderImpl(state);
    }

    public Certificate certificate() {
        return Certificate.get(this);
    }

    public boolean isValid() {
        return isValid(_encapsulated);
    }

    public boolean isValidAsEncapsulated() {
        return isValid(true);
    }

    private boolean isValid(boolean encapsulated) {
        if (filename == null) {
            return false;
        }
        return true;
    }

    // Getters
    public String getFilename() { return filename; }

    // Setters
    public void setFilename(String filename, Object mutator) { checkMutator(mutator); this.filename = filename; }

    private void checkMutator(Object mutator) {
        if (mutator != _encapsulator) {
            throw new IllegalStateException("The state can only be mutated by instance of " + (_encapsulator == null ? null : _encapsulator.getClass().getName()));
        }
    }


    public void encapsulate() {
        _encapsulated = true;
    }

    public void setEncapsulator(Object encapsulator) {
        _encapsulator = encapsulator;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        FileStateImpl state = (FileStateImpl)o;

        if (filename != null ? !filename.equals(state.filename) : state.filename != null) return false;

        return true;
    }

    public boolean valueEquals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        FileStateImpl state = (FileStateImpl)o;

        if (filename != null ? !filename.equals(state.filename) : state.filename != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = filename != null ? filename.hashCode() : 0;

        return result;
    }

    public int valueHashCode() {
        int result = filename != null ? filename.hashCode() : 0;

        return result;
    }

    @Override
    public String toString() {
        return "{filename=" + filename + "}";
    }
}
