package net.sf.laja.example.file.state;

import java.util.*;
import net.sf.laja.example.file.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class FileStateListImpl extends ArrayList<FileState> implements FileStateList {
    private boolean _encapsulated = false;

    FileStateListImpl() {
    }

    public static FileStateList emptyList(Certificate certificate) {
        return new FileStateListImpl();
    }

    public boolean isValid() {
        for (FileState state : this) {
            if (!state.isValid()) {
                return false;
            }
        }
        return true;
    }

    public void encapsulate() {
        _encapsulated = true;

        for (FileState state : this) {
            state.encapsulate();
        }
    }
}
