package net.sf.laja.example.file.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class FileStateProjection {

    FileStateProjection() {
    }

    public static FileStateProjection filename(String filename) {
        return new FileStateProjection();
    }
}
