package net.sf.laja.example.repository.state;

import net.sf.laja.example.repository.state.ZipcodeStateBuilder;
import net.sf.laja.example.repository.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface AddressStateBuilder extends ZipcodeStateBuilder {
    void withAddressId(int addressId);
    void withStreetName(String streetName);
    void withZipcode(int zipcode);
    void withCity(String city);
    boolean isValid();
    Object as(AddressStateBehaviourFactory factory, Object... args);
    AddressState getAddressState(net.sf.laja.example.repository.state.Certificate certificate);
}
