package net.sf.laja.example.repository.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class CustomerBehaviour {
    protected final CustomerState state;
    protected CustomerStateBuilder stateBuilder;

    public CustomerBehaviour(CustomerState state) {
        this.state = state;
        state.setEncapsulator(this);
    }

    public CustomerBehaviour(CustomerState state, CustomerStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
        state.setEncapsulator(this);
    }

    public CustomerState getState(Certificate certificate) {
        if (certificate == null) {
            throw new IllegalArgumentException("Certificate can not be null!");
        }
        return state;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.equals(((CustomerBehaviour)o).state);
    }

    @Override
    public int hashCode() {
        return state.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
