package net.sf.laja.example.repository.state;

import net.sf.laja.example.repository.state.Certificate;

import java.util.ArrayList;
import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public final class CustomerStateListBuilder {
    private Object lastMutator;
    private final Certificate certificate;
    private final CustomerStateList states;

    public CustomerStateListBuilder() {
        certificate = Certificate.get(new CustomerStateImpl());
        states = CustomerStateListImpl.emptyList(certificate);
    }

    public CustomerStateListBuilder(CustomerStateList states) {
        this.states = states;
        certificate = Certificate.get(new CustomerStateImpl());
    }

    public CustomerStateList getStateList(Certificate certificate) {
        return states;
    }

    public List<CustomerStateBuilder> getStateBuilders() {
        List<CustomerStateBuilder> builders = new ArrayList<CustomerStateBuilder>(states.size());

        for (CustomerState state : states) {
            builders.add(new CustomerStateBuilderImpl(state));
        }
        return builders;
    }

    public void throwExceptionIfOutOfSync(Object accessor) {
        if (lastMutator != null && lastMutator != accessor) {
            throw new IllegalStateException("The state has been changed by another list. Call syncState() to synchronize the internal state with the enclosing list.");
        }
    }

    private void prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(Object mutator) {
        throwExceptionIfOutOfSync(mutator);
        this.lastMutator = mutator;
    }

    public void syncState() {
        this.lastMutator = null;
    }

    public int size() {
        return states.size();
    }

    public void clear(Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.clear();
    }

    public void add(CustomerStateBuilder builder) {
        states.add(builder.getCustomerState(certificate));
    }

    public void add(CustomerState state) {
        states.add(state);
    }

    public void add(CustomerState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(state);
    }

    public void add(int index, CustomerState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(index, state);
    }

    public void addAll(int index, CustomerStateListBuilder listBuilder, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.addAll(index, listBuilder.states);
    }

    public void set(int index, CustomerState state, Object accessor) {
        throwExceptionIfOutOfSync(accessor);
        states.set(index, state);
    }

    public boolean remove(CustomerState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        return states.remove(state);
    }

    public void remove(int index, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.remove(index);
    }

    public void retainAll(CustomerStateListBuilder retainStates, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "CustomerStateListBuilder{states=" + states + ", lastMutator.hashCode()=" + (lastMutator == null ? null : lastMutator.hashCode()) + "}";
    }
}
