package net.sf.laja.example.repository.state;

import net.sf.laja.example.repository.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class CustomerValue implements CustomerElement {
    protected final CustomerState state;
    protected CustomerStateBuilder stateBuilder;

    public CustomerValue(CustomerState state) {
        this.state = state;
        state.setEncapsulator(this);
    }

    public CustomerValue(CustomerState state, CustomerStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
        state.setEncapsulator(this);
    }

    public CustomerState getState(Certificate certificate) {
        if (certificate == null) {
            throw new IllegalArgumentException("Certificate can not be null!");
        }
        return state;
    }

    public CustomerState getState(CustomerStateList stateList) {
        if (stateList == null) {
            throw new IllegalArgumentException("CustomerStateList can not be null!");
        }
        return state;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.valueEquals(((CustomerValue)o).state);
    }

    @Override
    public int hashCode() {
        return state.valueHashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
