package net.sf.laja.example.repository.state;

import net.sf.laja.example.repository.state.Certificate;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public final class ZipcodeStateSetBuilder {
    private final Certificate certificate;
    private final ZipcodeStateSet states;

    public ZipcodeStateSetBuilder() {
        certificate = Certificate.get(new ZipcodeStateImpl());
        states = ZipcodeStateHashSet.emptySet();
    }

    public ZipcodeStateSetBuilder(ZipcodeStateSet states) {
        this.states = states;
        certificate = Certificate.get(new ZipcodeStateImpl());
    }

    public ZipcodeStateSet getStateSet(Certificate certificate) {
        return states;
    }

    public List<ZipcodeStateBuilder> getStateBuilders() {
        List<ZipcodeStateBuilder> builders = new ArrayList<ZipcodeStateBuilder>(states.size());

        for (ZipcodeState state : states) {
            builders.add(new ZipcodeStateBuilderImpl(state));
        }
        return builders;
    }

    public int size() {
        return states.size();
    }

    public void clear() {
        states.clear();
    }

    public void add(ZipcodeStateBuilder builder) {
        states.add(builder.getZipcodeState(certificate));
    }

    public void add(ZipcodeState state) {
        states.add(state);
    }

    public boolean remove(ZipcodeState state) {
        return states.remove(state);
    }

    public void remove(int index) {
        states.remove(index);
    }

    public void retainAll(ZipcodeStateSetBuilder retainStates) {
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "ZipcodeStateSetBuilder{" + states + "}";
    }
}
