package net.sf.laja.cdd.behaviour.xhand;

import net.sf.laja.cdd.state.xhand.*;
import net.sf.laja.cdd.behaviour.xhand.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class XHandHashSet implements XHandSet, RandomAccess, Cloneable, java.io.Serializable {
    protected XHandStateSet stateSet;
    protected final Set<XHand> set;

    public XHandHashSet(XHand... array) {
        this.set = new HashSet<XHand>();
        this.set.addAll(Arrays.asList(array));
    }

    public XHandHashSet(Collection<XHand> collection) {
        this.set = new HashSet<XHand>();
        this.set.addAll(collection);
    }

    public XHandHashSet(XHandStateSet stateSet) {
        this.stateSet = stateSet;
        this.stateSet.encapsulate(this);
        Set<XHand> elements = new HashSet<XHand>(stateSet.size());

        for (XHandState state : stateSet) {
            XHandStateBuilder builder = new XHandStateBuilderImpl(state);
            XHand entry = (XHand) builder.as(new XHandFactory.XHandFactory_(builder));
            elements.add(entry);
        }
        this.set = new StateInSyncSet(stateSet, elements);
    }

    public class StateInSyncSet extends HashSet<XHand> {
        private XHandStateSet stateSet;

        public StateInSyncSet(XHandStateSet stateSet, Set<XHand> elements) {
            this.stateSet = stateSet;
            this.stateSet.clear();
            super.addAll(elements);
        }

        @Override
        public boolean add(XHand element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(XHandHashSet.this);
            stateSet.add(element.getState(stateSet.certificate()));
            return super.add(element);
        }

        @Override
        public boolean addAll(Collection<? extends XHand> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(XHandHashSet.this);
            boolean modified = super.addAll(collection);

            for (XHand element : collection) {
                stateSet.add(element.getState(stateSet.certificate()));
            }
            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(XHandHashSet.this);
            if (!(element instanceof XHand)) {
                return false;
            }
            boolean removedState = stateSet.remove(((XHand) element).getState(stateSet.certificate()));
            boolean removedElement = super.remove(element);

            if (removedState != removedElement) {
                throw new IllegalStateException("The state and behaviour is out of sync. Please report this bug to the Laja project!");
            }
            return removedElement;
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(XHandHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof XHand) {
                    elements.add(element);
                    states.add(((XHand)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateSet.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(XHandHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof XHand) {
                    elements.add(element);
                    states.add(((XHand)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateSet.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateSet.throwExceptionIfNotEncapsulatedBy(XHandHashSet.this);
            stateSet.clear();
            super.clear();
        }
    }

    public int size() {
        return set.size();
    }

    public boolean isEmpty() {
        return set.isEmpty();
    }

    public boolean contains(Object element) {
        return set.contains(element);
    }

    public Iterator<XHand> iterator() {
        return set.iterator();
    }

    public Object[] toArray() {
        return set.toArray();
    }

    public <XHand> XHand[] toArray(XHand[] array) {
        return set.toArray(array);
    }

    public boolean add(XHand element) {
        return set.add(element);
    }

    public boolean addAll(Collection<? extends XHand> collection) {
        return set.addAll(collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof XHand)) {
            return false;
        }
        return set.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return set.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return set.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return set.retainAll(collection);
    }

    public void clear() {
        set.clear();
    }

    @Override
    public boolean equals(Object o) {
        return set.equals(o);
    }

    @Override
    public int hashCode() {
        return set.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + set + '}';
    }
}
