package net.sf.laja.cdd.behaviour.finger;

import net.sf.laja.cdd.state.finger.*;
import net.sf.laja.cdd.behaviour.finger.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class FingerArrayList implements FingerList, RandomAccess, Cloneable, java.io.Serializable {
    protected FingerStateList stateList;
    protected final List<Finger> list;

    public FingerArrayList(Finger... array) {
        this.list = new ArrayList<Finger>();
        this.list.addAll(Arrays.asList(array));
    }

    public FingerArrayList(Collection<Finger> collection) {
        this.list = new ArrayList<Finger>();
        this.list.addAll(collection);
    }

    public FingerArrayList(FingerStateList stateList) {
        this.stateList = stateList;
        this.stateList.encapsulate(this);
        List<Finger> elements = new ArrayList<Finger>(stateList.size());

        for (FingerState state : stateList) {
            FingerStateBuilder builder = new FingerStateBuilderImpl(state);
            Finger entry = (Finger) builder.as(new FingerFactory.FingerFactory_(builder));
            elements.add(entry);
        }
        this.list = new StateInSyncList(stateList, elements);
    }

    public class StateInSyncList extends ArrayList<Finger> {
        private final FingerStateList stateList;

        public StateInSyncList(FingerStateList stateList, List<Finger> elements) {
            this.stateList = stateList;
            super.addAll(elements);
        }

        @Override
        public boolean add(Finger element) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            stateList.add(element.getState(stateList.certificate()));
            return super.add(element);
        }

        @Override
        public void add(int index, Finger element) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            stateList.add(index, element.getState(stateList.certificate()));
            super.add(index, element);
        }

        @Override
        public boolean addAll(Collection<? extends Finger> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            boolean modified = super.addAll(collection);

            for (Finger element : collection) {
                stateList.add(element.getState(stateList.certificate()));
            }
            return modified;
        }

        @Override
        public boolean addAll(int index, Collection<? extends Finger> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            boolean modified = super.addAll(index, collection);

            List elements = new ArrayList(collection.size());
            for (Finger element : collection) {
                elements.add(element.getState(stateList.certificate()));
            }
            stateList.addAll(index, elements);

            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            if (!(element instanceof Finger)) {
                return false;
            }
            stateList.remove(((Finger) element).getState(stateList.certificate()));

            return super.remove(element);
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof Finger) {
                    elements.add(element);
                    states.add(((Finger)element).getState(stateList.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateList.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof Finger) {
                    elements.add(element);
                    states.add(((Finger)element).getState(stateList.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateList.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            stateList.clear();
            super.clear();
        }

        @Override
        public Finger set(int index, Finger element) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            stateList.set(index, element.getState(stateList.certificate()));
            return super.set(index, element);
        }

        @Override
        public Finger remove(int index) {
            stateList.throwExceptionIfNotEncapsulatedBy(FingerArrayList.this);
            stateList.remove(index);
            return super.remove(index);
        }
    }

    public int size() {
        return list.size();
    }

    public boolean isEmpty() {
        return list.isEmpty();
    }

    public boolean contains(Object element) {
        return list.contains(element);
    }

    public Iterator<Finger> iterator() {
        return list.iterator();
    }

    public Object[] toArray() {
        return list.toArray();
    }

    public <Finger> Finger[] toArray(Finger[] array) {
        return list.toArray(array);
    }

    public boolean add(Finger element) {
        return list.add(element);
    }

    public void add(int index, Finger element) {
        list.add(index, element);
    }

    public boolean addAll(Collection<? extends Finger> collection) {
        return list.addAll(collection);
    }

    public boolean addAll(int index, Collection<? extends Finger> collection) {
        return list.addAll(index, collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof Finger)) {
            return false;
        }
        return list.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return list.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return list.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return list.retainAll(collection);
    }

    public void clear() {
        list.clear();
    }

    public Finger get(int index) {
        return list.get(index);
    }

    public Finger set(int index, Finger element) {
        return list.set(index, element);
    }

    public Finger remove(int index) {
        return list.remove(index);
    }

    public int indexOf(Object element) {
        return list.indexOf(element);
    }

    public int lastIndexOf(Object element) {
        return list.lastIndexOf(element);
    }

    public ListIterator<Finger> listIterator() {
        return list.listIterator();
    }

    public ListIterator<Finger> listIterator(int index) {
        return list.listIterator(index);
    }

    public List<Finger> subList(int fromIndex, int toIndex) {
        return list.subList(fromIndex, toIndex);
    }

    @Override
    public boolean equals(Object o) {
        return list.equals(o);
    }

    @Override
    public int hashCode() {
        return list.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + list + '}';
    }
}
