package net.sf.laja.cdd.state.forehead;

import net.sf.laja.cdd.state.brow.BrowStateList;
import net.sf.laja.cdd.state.brow.BrowStateBuilder;
import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface ForeheadStateBuilder {
    void withBrows(net.sf.laja.cdd.state.brow.BrowStateListBuilder listBuilder);
    boolean isValid();
    Object as(ForeheadStateBehaviourFactory factory, Object... args);
    ForeheadState getForeheadState(net.sf.laja.cdd.state.Certificate certificate);
}
