package net.sf.laja.cdd.state.forehead;

import net.sf.laja.cdd.state.brow.BrowStateList;
import net.sf.laja.cdd.state.Certificate;
import net.sf.laja.cdd.state.brow.BrowStateList;
import net.sf.laja.cdd.state.brow.BrowStateListImpl;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class ForeheadStateProjection {

    ForeheadStateProjection() {
    }

    public static ForeheadStateProjection brows(BrowStateList brows) {
        return new ForeheadStateProjection();
    }
}
