package net.sf.laja.cdd.behaviour.animal;

import net.sf.laja.cdd.state.animal.*;
import net.sf.laja.cdd.behaviour.animal.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class AnimalHashSet implements AnimalSet, RandomAccess, Cloneable, java.io.Serializable {
    protected AnimalStateSet stateSet;
    protected final Set<Animal> set;

    public AnimalHashSet(Animal... array) {
        this.set = new HashSet<Animal>();
        this.set.addAll(Arrays.asList(array));
    }

    public AnimalHashSet(Collection<Animal> collection) {
        this.set = new HashSet<Animal>();
        this.set.addAll(collection);
    }

    public AnimalHashSet(AnimalStateSet stateSet) {
        this.stateSet = stateSet;
        this.stateSet.encapsulate(this);
        Set<Animal> elements = new HashSet<Animal>(stateSet.size());

        for (AnimalState state : stateSet) {
            AnimalStateBuilder builder = new AnimalStateBuilderImpl(state);
            Animal entry = (Animal) builder.as(new AnimalFactory.AnimalFactory_());
            elements.add(entry);
        }
        this.set = new StateInSyncSet(stateSet, elements);
    }

    public class StateInSyncSet extends HashSet<Animal> {
        private AnimalStateSet stateSet;

        public StateInSyncSet(AnimalStateSet stateSet, Set<Animal> elements) {
            this.stateSet = stateSet;
            this.stateSet.clear();
            super.addAll(elements);
        }

        @Override
        public boolean add(Animal element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(AnimalHashSet.this);
            stateSet.add(element.getState(stateSet.certificate()));
            return super.add(element);
        }

        @Override
        public boolean addAll(Collection<? extends Animal> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(AnimalHashSet.this);
            boolean modified = super.addAll(collection);

            for (Animal element : collection) {
                stateSet.add(element.getState(stateSet.certificate()));
            }
            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(AnimalHashSet.this);
            if (!(element instanceof Animal)) {
                return false;
            }
            boolean removedState = stateSet.remove(((Animal) element).getState(stateSet.certificate()));
            boolean removedElement = super.remove(element);

            if (removedState != removedElement) {
                throw new IllegalStateException("The state and behaviour is out of sync. Please report this bug to the Laja project!");
            }
            return removedElement;
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(AnimalHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof Animal) {
                    elements.add(element);
                    states.add(((Animal)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateSet.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(AnimalHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof Animal) {
                    elements.add(element);
                    states.add(((Animal)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateSet.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateSet.throwExceptionIfNotEncapsulatedBy(AnimalHashSet.this);
            stateSet.clear();
            super.clear();
        }
    }

    public int size() {
        return set.size();
    }

    public boolean isEmpty() {
        return set.isEmpty();
    }

    public boolean contains(Object element) {
        return set.contains(element);
    }

    public Iterator<Animal> iterator() {
        return set.iterator();
    }

    public Object[] toArray() {
        return set.toArray();
    }

    public <Animal> Animal[] toArray(Animal[] array) {
        return set.toArray(array);
    }

    public boolean add(Animal element) {
        return set.add(element);
    }

    public boolean addAll(Collection<? extends Animal> collection) {
        return set.addAll(collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof Animal)) {
            return false;
        }
        return set.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return set.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return set.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return set.retainAll(collection);
    }

    public void clear() {
        set.clear();
    }

    @Override
    public boolean equals(Object o) {
        return set.equals(o);
    }

    @Override
    public int hashCode() {
        return set.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + set + '}';
    }
}
