package net.sf.laja.cdd.behaviour.mouth;

import net.sf.laja.cdd.state.mouth.*;

import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public abstract class MouthAbstractList implements List<Mouth> {
    protected MouthStateList stateList;
    protected final List<Mouth> list = new ArrayList<Mouth>();

    public MouthAbstractList(Mouth... list) {
        this.list.addAll(Arrays.asList(list));
    }

    public MouthAbstractList(List<Mouth> list) {
        this.list.addAll(list);
    }


    public MouthAbstractList(MouthStateList stateList, MouthSize size) {
        this.stateList = stateList;

        for (MouthState state : stateList) {
            MouthStateBuilder builder = new MouthStateBuilderImpl(state);
            Mouth entry = (Mouth) builder.as(new MouthFactory.MouthFactory_(builder), size);
            list.add(entry);
        }
    }

    public CuteMouthList asCuteMouthList(MouthSize size, int x) {
        List<CuteMouth> result = new ArrayList<CuteMouth>();
        for (Mouth entry : list) {
            result.add(entry.asCuteMouth(size, x));
        }
        return new CuteMouthList(result);
    }

    public boolean isStateInSync() {
        if (stateList == null) {
            return true;
        }
        if (stateList.size() != list.size()) {
            return false;
        }
        for (Mouth element : list) {
            if (!element.contains(stateList) || !element.isStateInSync()) {
                return false;
            }
        }
        return true;
    }

    public boolean syncState() {
        if (isStateInSync()) {
            return false;
        }
        stateList.clear();

        for (Mouth entry : list) {
            entry.syncState();
            entry.addToList(stateList);
        }
        return true;
    }

    public int size() {
        return list.size();
    }

    public boolean isEmpty() {
        return list.isEmpty();
    }

    public boolean contains(Object element) {
        return list.contains(element);
    }

    public Iterator<Mouth> iterator() {
        return list.iterator();
    }

    public Object[] toArray() {
        return list.toArray();
    }

    public <Mouth> Mouth[] toArray(Mouth[] array) {
        return list.toArray(array);
    }

    public boolean add(Mouth element) {
        return list.add(element);
    }

    public void add(int index, Mouth element) {
        list.add(index, element);
    }

    public boolean addAll(Collection<? extends Mouth> collection) {
        return list.addAll(collection);
    }

    public boolean addAll(int index, Collection<? extends Mouth> collection) {
        return list.addAll(index, collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof Mouth)) {
            return false;
        }
        return list.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return list.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return list.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return list.retainAll(collection);
    }

    public void clear() {
        list.clear();
    }

    public Mouth get(int index) {
        return list.get(index);
    }

    public Mouth set(int index, Mouth element) {
        return list.set(index, element);
    }

    public Mouth remove(int index) {
        return list.remove(index);
    }

    public int indexOf(Object element) {
        return list.indexOf(element);
    }

    public int lastIndexOf(Object element) {
        return list.lastIndexOf(element);
    }

    public ListIterator<Mouth> listIterator() {
        return list.listIterator();
    }

    public ListIterator<Mouth> listIterator(int index) {
        return list.listIterator(index);
    }

    public List<Mouth> subList(int fromIndex, int toIndex) {
        return list.subList(fromIndex, toIndex);
    }

    @Override
    public boolean equals(Object o) {
        return list.equals(o);
    }

    @Override
    public int hashCode() {
        return list.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{list=" + list + '}';
    }
}
