package net.sf.laja.cdd.state.terrestrial;

import net.sf.laja.cdd.state.eye.EyeState;
import net.sf.laja.cdd.state.eye.EyeStateBuilder;
import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface TerrestrialStateBuilder {
    void withNumberOfLegs(int numberOfLegs);
    void withNumberOfWings(int numberOfWings);
    void withLeftEye(EyeStateBuilder leftEye);
    void withRightEye(EyeStateBuilder rightEye);
    void withMiddleEye(EyeStateBuilder middleEye);
    void withWeight(int weight);
    EyeStateBuilder getLeftEyeStateBuilder();
    EyeStateBuilder getRightEyeStateBuilder();
    EyeStateBuilder getMiddleEyeStateBuilder();
    boolean isValid();
    Object as(TerrestrialStateBehaviourFactory factory, Object... args);
    TerrestrialState getTerrestrialState(net.sf.laja.cdd.state.Certificate certificate);
}
