package net.sf.laja.cdd.state.ear;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface EarBehaviourFactory {
    Object create(EarState state, Object... args);
}
