package net.sf.laja.cdd.state.ear;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class EarStateProjection {

    EarStateProjection() {
    }

    public static EarStateProjection size(double size) {
        return new EarStateProjection();
    }
}
