package net.sf.laja.cdd.state.ear;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface EarStateBehaviourFactory {
    Object create(EarState state, Object... args);
}
