package net.sf.laja.cdd.state.foot;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface FootBehaviourFactory {
    Object create(FootState state, Object... args);
}
