package net.sf.laja.cdd.state.foot;

import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class FootValue implements FootElement {
    protected final FootState state;
    protected FootStateBuilder stateBuilder;

    public FootValue(FootState state) {
        this.state = state;
    }

    public FootValue(FootState state, FootStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
    }

    public boolean contains(FootStateList stateList) {
        return stateList.contains(state);
    }

    public FootState getState(Certificate certificate) {
        return state;
    }

    public FootState getState(FootStateList stateList) {
        return state;
    }

    public void addToList(FootStateList stateList) {
        stateList.add(state);
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.valueEquals(((FootValue)o).state);
    }

    @Override
    public int hashCode() {
        return state.valueHashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
