package net.sf.laja.cdd.state.arm;

import net.sf.laja.cdd.state.Certificate;
import net.sf.laja.cdd.state.hand.HandStateList;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface ArmState {
    int getArmLength(); // (optional)
    void setArmLength(int armLength);

    double getArmWeight();
    void setArmWeight(double armWeight);

    HandStateList getHands();
    void setHands(HandStateList hands);

    boolean isValid();
    boolean isValidAsEncapsulated();
    boolean valueEquals(Object o);
    int valueHashCode();
    void encapsulate();
    Certificate certificate();
}
