package net.sf.laja.cdd.state.hand;

import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface HandStateBuilder extends HandStateComparable {
    void withArea(int area);
    boolean isValid();
    Object as(HandBehaviourFactory factory, Object... args);
    HandState getHandState(net.sf.laja.cdd.state.Certificate certificate);
}
