package net.sf.laja.cdd.behaviour.brow;

import net.sf.laja.cdd.state.brow.*;

import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public abstract class BrowAbstractList implements List<Brow> {
    protected BrowStateList stateList;
    protected final List<Brow> list = new ArrayList<Brow>();

    public BrowAbstractList(Brow... list) {
        this.list.addAll(Arrays.asList(list));
    }

    public BrowAbstractList(List<Brow> list) {
        this.list.addAll(list);
    }


    public BrowAbstractList(BrowStateList stateList) {
        this.stateList = stateList;

        for (BrowState state : stateList) {
            BrowStateBuilder builder = new BrowStateBuilderImpl(state);
            Brow entry = (Brow) builder.as(new BrowFactory.BrowFactory_(builder));
            list.add(entry);
        }
    }

    public boolean isStateInSync() {
        if (stateList == null) {
            return true;
        }
        if (stateList.size() != list.size()) {
            return false;
        }
        for (Brow element : list) {
            if (!element.contains(stateList) || !element.isStateInSync()) {
                return false;
            }
        }
        return true;
    }

    public boolean syncState() {
        if (isStateInSync()) {
            return false;
        }
        stateList.clear();

        for (Brow entry : list) {
            entry.syncState();
            entry.addToList(stateList);
        }
        return true;
    }

    public int size() {
        return list.size();
    }

    public boolean isEmpty() {
        return list.isEmpty();
    }

    public boolean contains(Object element) {
        return list.contains(element);
    }

    public Iterator<Brow> iterator() {
        return list.iterator();
    }

    public Object[] toArray() {
        return list.toArray();
    }

    public <Brow> Brow[] toArray(Brow[] array) {
        return list.toArray(array);
    }

    public boolean add(Brow element) {
        return list.add(element);
    }

    public void add(int index, Brow element) {
        list.add(index, element);
    }

    public boolean addAll(Collection<? extends Brow> collection) {
        return list.addAll(collection);
    }

    public boolean addAll(int index, Collection<? extends Brow> collection) {
        return list.addAll(index, collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof Brow)) {
            return false;
        }
        return list.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return list.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return list.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return list.retainAll(collection);
    }

    public void clear() {
        list.clear();
    }

    public Brow get(int index) {
        return list.get(index);
    }

    public Brow set(int index, Brow element) {
        return list.set(index, element);
    }

    public Brow remove(int index) {
        return list.remove(index);
    }

    public int indexOf(Object element) {
        return list.indexOf(element);
    }

    public int lastIndexOf(Object element) {
        return list.lastIndexOf(element);
    }

    public ListIterator<Brow> listIterator() {
        return list.listIterator();
    }

    public ListIterator<Brow> listIterator(int index) {
        return list.listIterator(index);
    }

    public List<Brow> subList(int fromIndex, int toIndex) {
        return list.subList(fromIndex, toIndex);
    }

    @Override
    public boolean equals(Object o) {
        return list.equals(o);
    }

    @Override
    public int hashCode() {
        return list.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{list=" + list + '}';
    }
}
