package net.sf.laja.cdd.state.finger;

import net.sf.laja.cdd.state.nail.NailState;
import net.sf.laja.cdd.state.nail.NailState;
import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface FingerState extends FingerStateComparable, NailState {
    String getColor();
    void setColor(String color, Object mutator);
    NailState getNailState();
}
