package net.sf.laja.cdd.state.finger;

import net.sf.laja.cdd.state.nail.NailState;
import net.sf.laja.cdd.state.nail.NailBehaviourFactory;
import net.sf.laja.cdd.state.nail.NailState;
import net.sf.laja.cdd.state.nail.NailStateBuilder;
import net.sf.laja.cdd.state.nail.NailStateBuilderImpl;
import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class FingerStateBuilderImpl implements FingerStateBuilder {
    private Object encapsulator;
    private FingerState state;
    private final Certificate certificate;

    FingerStateBuilderImpl() {
        state = new FingerStateImpl();
        certificate = Certificate.get(this);
    }

    public FingerStateBuilderImpl(FingerState state) {
        this.state = state;
        certificate = Certificate.get(this);
    }

    public FingerStateBuilderImpl(FingerState state, Object encapsulator) {
        this(state);
        this.encapsulator = encapsulator;
    }

    public NailStateBuilder getNailStateBuilder() {
        return new NailStateBuilderImpl(state.getNailState());
    }

    public void withColor(String color) {
        state.setColor(color, encapsulator);
    }

    public boolean isValid() {
        return state.isValid();
    }

    public Object as(FingerBehaviourFactory factory, Object... args) {
        return factory.create(state, args);
    }

    public FingerState getFingerState(net.sf.laja.cdd.state.Certificate certificate) {
        return state;
    }

    @Override
    public int hashCode() {
        return state.hashCode();
    }
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof FingerStateComparable)) return false;

        return true;
    }

    @Override
    public String toString() {
        return state.toString();
    }
}
