package net.sf.laja.example.person.state;

import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface BmiStateList extends List<BmiState> {
    Certificate certificate();
    boolean isValid();
    void encapsulate();
}
