package net.sf.laja.example.person.state;

import net.sf.laja.example.person.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface HeightStateBuilder {
    void withHeightInCentimeters(int heightInCentimeters);
    boolean isValid();
    Object as(HeightStateBehaviourFactory factory, Object... args);
    HeightState getHeightState(net.sf.laja.example.person.state.Certificate certificate);
}
