package net.sf.laja.example.person.state;

import net.sf.laja.example.person.state.BmiState;
import net.sf.laja.example.person.state.HeightState;
import net.sf.laja.example.person.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface PersonState {
    String getGivenName();
    void setGivenName(String givenName, Object mutator);

    String getSurname();
    void setSurname(String surname, Object mutator);

    int getWeightInKilograms();
    void setWeightInKilograms(int weightInKilograms, Object mutator);

    HeightState getHeight();
    void setHeight(HeightState height, Object mutator);

    BmiState getBmiState();

    boolean isValid();
    boolean isValidAsEncapsulated();
    boolean equalsValue(Object obj);
    void encapsulate();
    void setEncapsulator(Object encapsulator);
    Certificate certificate();
}
