package net.sf.laja.example.person.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface PersonStateBuilder {
    void withGivenName(String givenName);
    void withSurname(String surname);
    void withSize(BmiStateBuilder size);
    BmiStateBuilder getSizeStateBuilder();
    boolean isValid();
    Object as(PersonBehaviourFactory factory, Object... args);
    PersonState getPersonState(net.sf.laja.example.person.state.Certificate certificate);
}
