package net.sf.laja.example.person.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class PersonStateBuilderImpl implements PersonStateBuilder {
    private Object encapsulator;
    private PersonState state;
    private final Certificate certificate;
    private BmiStateBuilder sizeStateBuilder;

    PersonStateBuilderImpl() {
        state = new PersonStateImpl();
        certificate = Certificate.get(this);
    }

    public PersonStateBuilderImpl(PersonState state) {
        this.state = state;
        certificate = Certificate.get(this);
    }

    public PersonStateBuilderImpl(PersonState state, Object encapsulator) {
        this(state);
        this.encapsulator = encapsulator;
    }

    public void withGivenName(String givenName) {
        state.setGivenName(givenName, encapsulator);
    }

    public void withSurname(String surname) {
        state.setSurname(surname, encapsulator);
    }

    public void withSize(BmiStateBuilder size) {
        state.setSize(size.getBmiState(certificate), encapsulator);
    }

    public BmiStateBuilder getSizeStateBuilder() {
        if (sizeStateBuilder == null) {
            sizeStateBuilder = new BmiStateBuilderImpl(state.getSize());
        }
        return sizeStateBuilder;
    }

    public boolean isValid() {
        return state.isValid();
    }

    public Object as(PersonBehaviourFactory factory, Object... args) {
        return factory.create(state, args);
    }

    public PersonState getPersonState(net.sf.laja.example.person.state.Certificate certificate) {
        return state;
    }

    @Override
    public int hashCode() {
        return state.hashCode();
    }
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof PersonStateComparable)) return false;

        return true;
    }

    @Override
    public String toString() {
        return state.toString();
    }
}
