package net.sf.laja.example.person.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class PersonStateBuilderImpl implements PersonStateBuilder {
    private Object encapsulator;
    private PersonState state;
    private final Certificate certificate;
    private HeightStateBuilder heightStateBuilder;

    PersonStateBuilderImpl() {
        state = new PersonStateImpl();
        certificate = Certificate.get(this);
    }

    public PersonStateBuilderImpl(PersonState state) {
        this.state = state;
        certificate = Certificate.get(this);
    }

    public PersonStateBuilderImpl(PersonState state, Object encapsulator) {
        this(state);
        this.encapsulator = encapsulator;
    }

    public BmiStateBuilder bmiStateBuilder() {
        return new BmiStateBuilderImpl(state.getBmiState());
    }

    public void withGivenName(String givenName) {
        state.setGivenName(givenName, encapsulator);
    }

    public void withSurname(String surname) {
        state.setSurname(surname, encapsulator);
    }

    public void withWeightInKilograms(int weightInKilograms) {
        state.setWeightInKilograms(weightInKilograms, encapsulator);
    }

    public void withHeight(HeightStateBuilder height) {
        state.setHeight(height.getHeightState(certificate), encapsulator);
    }

    public HeightStateBuilder getHeightStateBuilder() {
        if (heightStateBuilder == null) {
            heightStateBuilder = new HeightStateBuilderImpl(state.getHeight());
        }
        return heightStateBuilder;
    }

    public boolean isValid() {
        return state.isValid();
    }

    public Object as(PersonStateBehaviourFactory factory, Object... args) {
        return factory.create(state, args);
    }

    public PersonState getPersonState(net.sf.laja.example.person.state.Certificate certificate) {
        return state;
    }
}
