package net.sf.laja.cdd.state.fleck;

import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class FleckValue implements FleckElement {
    protected final FleckState state;
    protected FleckStateBuilder stateBuilder;

    public FleckValue(FleckState state) {
        this.state = state;
    }

    public FleckValue(FleckState state, FleckStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
    }

    public boolean contains(FleckStateList stateList) {
        return stateList.contains(state);
    }

    public FleckState getState(Certificate certificate) {
        return state;
    }

    public FleckState getState(FleckStateList stateList) {
        return state;
    }

    public void addToList(FleckStateList stateList) {
        stateList.add(state);
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.valueEquals(((FleckValue)o).state);
    }

    @Override
    public int hashCode() {
        return state.valueHashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
