package net.sf.laja.cdd.state.fleck;

import java.util.ArrayList;
import java.util.List;
import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public final class FleckStateListBuilder {
    private final Certificate certificate;
    private final FleckStateList states;

    public FleckStateListBuilder() {
        certificate = Certificate.get(new FleckStateImpl());
        states = FleckStateArrayList.emptyList();
    }

    public FleckStateListBuilder(FleckStateList states) {
        this.states = states;
        certificate = Certificate.get(new FleckStateImpl());
    }

    public FleckStateList getStateList(Certificate certificate) {
        return states;
    }

    public List<FleckStateBuilder> getStateBuilders() {
        List<FleckStateBuilder> builders = new ArrayList<FleckStateBuilder>(states.size());

        for (FleckState state : states) {
            builders.add(new FleckStateBuilderImpl(state));
        }
        return builders;
    }

    public int size() {
        return states.size();
    }

    public void clear() {
        states.clear();
    }

    public void add(FleckStateBuilder builder) {
        states.add(builder.getFleckState(certificate));
    }

    public void add(FleckState state) {
        states.add(state);
    }

    public void add(int index, FleckState state) {
        states.add(index, state);
    }

    public void addAll(int index, FleckStateListBuilder listBuilder) {
        states.addAll(index, listBuilder.states);
    }

    public void set(int index, FleckState state) {
        states.set(index, state);
    }

    public boolean remove(FleckState state) {
        return states.remove(state);
    }

    public void remove(int index) {
        states.remove(index);
    }

    public void retainAll(FleckStateListBuilder retainStates) {
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "FleckStateListBuilder{" + states + "}";
    }
}
