package net.sf.laja.cdd.state.fleck;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface FleckStateBehaviourFactory {
    Object create(FleckState state, Object... args);
}
