package net.sf.laja.cdd.state.monster;

import net.sf.laja.cdd.state.Certificate;

import java.util.ArrayList;
import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public final class MonsterStateListBuilder {
    private final Certificate certificate;
    private final MonsterStateList states;

    public MonsterStateListBuilder() {
        certificate = Certificate.get(new MonsterStateImpl());
        states = MonsterStateArrayList.emptyList();
    }

    public MonsterStateListBuilder(MonsterStateList states) {
        this.states = states;
        certificate = Certificate.get(new MonsterStateImpl());
    }

    public MonsterStateList getStateList(Certificate certificate) {
        return states;
    }

    public List<MonsterStateBuilder> getStateBuilders() {
        List<MonsterStateBuilder> builders = new ArrayList<MonsterStateBuilder>(states.size());

        for (MonsterState state : states) {
            builders.add(new MonsterStateBuilderImpl(state));
        }
        return builders;
    }

    public int size() {
        return states.size();
    }

    public void clear() {
        states.clear();
    }

    public void add(MonsterStateBuilder builder) {
        states.add(builder.getMonsterState(certificate));
    }

    public void add(MonsterState state) {
        states.add(state);
    }

    public void add(int index, MonsterState state) {
        states.add(index, state);
    }

    public void addAll(int index, MonsterStateListBuilder listBuilder) {
        states.addAll(index, listBuilder.states);
    }

    public void set(int index, MonsterState state) {
        states.set(index, state);
    }

    public boolean remove(MonsterState state) {
        return states.remove(state);
    }

    public void remove(int index) {
        states.remove(index);
    }

    public void retainAll(MonsterStateListBuilder retainStates) {
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "MonsterStateListBuilder{" + states + "}";
    }
}
