package net.sf.laja.cdd.state.toe;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface ToeStateBehaviourFactory {
    Object create(ToeState state, Object... args);
}
