package net.sf.laja.cdd.state.toe;

import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class ToeStateBuilderImpl implements ToeStateBuilder {
    private Object encapsulator;
    private ToeState state;
    private final Certificate certificate;

    ToeStateBuilderImpl() {
        state = new ToeStateImpl();
        certificate = Certificate.get(this);
    }

    public ToeStateBuilderImpl(ToeState state) {
        this.state = state;
        certificate = Certificate.get(this);
    }

    public ToeStateBuilderImpl(ToeState state, Object encapsulator) {
        this(state);
        this.encapsulator = encapsulator;
    }

    public void withLength(int length) {
        state.setLength(length, encapsulator);
    }

    public void withWeight(int weight) {
        state.setWeight(weight, encapsulator);
    }

    public boolean isValid() {
        return state.isValid();
    }

    public Object as(ToeBehaviourFactory factory, Object... args) {
        return factory.create(state, args);
    }

    public ToeState getToeState(net.sf.laja.cdd.state.Certificate certificate) {
        return state;
    }

    @Override
    public int hashCode() {
        return state.hashCode();
    }
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof ToeStateComparable)) return false;

        return true;
    }

    @Override
    public String toString() {
        return state.toString();
    }
}
