package net.sf.laja.cdd.state.eye;

import java.math.BigDecimal;
import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface EyeStateBuilder {
    void withEyeWeightInGrams(int eyeWeightInGrams);
    void withEyeWeightInGrams(String eyeWeightInGrams);
    void withColor(String color);
    void withColor(BigDecimal color);
    void withColor(int color);
    void withDecease(String decease);
    void withDecease(int decease);
    void withHasEar(Boolean hasEar);
    boolean isValid();
    Object as(EyeStateBehaviourFactory factory, Object... args);
    EyeState getEyeState(net.sf.laja.cdd.state.Certificate certificate);
}
