package net.sf.laja.cdd.state.head;

import net.sf.laja.cdd.state.eye.EyeState;
import net.sf.laja.cdd.state.eye.EyeState;
import net.sf.laja.cdd.state.eye.EyeState;
import net.sf.laja.cdd.state.nose.NoseStateList;
import net.sf.laja.cdd.state.forehead.ForeheadState;
import net.sf.laja.cdd.state.ear.EarStateList;
import net.sf.laja.cdd.state.mouth.MouthStateList;
import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface HeadState {
    double getHeadWeightInGrams();
    void setHeadWeightInGrams(double headWeightInGrams, Object mutator);

    EyeState getLeftEye();
    void setLeftEye(EyeState leftEye, Object mutator);

    EyeState getRightEye();
    void setRightEye(EyeState rightEye, Object mutator);

    EyeState getMidEye(); // (optional)
    void setMidEye(EyeState midEye, Object mutator);

    NoseStateList getNoses();
    void setNoses(NoseStateList noses, Object mutator);

    ForeheadState getForehead();
    void setForehead(ForeheadState forehead, Object mutator);

    int getLength(); // (optional)
    void setLength(int length, Object mutator);

    boolean getA();
    void setA(boolean a, Object mutator);

    byte getB();
    void setB(byte b, Object mutator);

    short getC();
    void setC(short c, Object mutator);

    char getD();
    void setD(char d, Object mutator);

    int getE(); // (hidden)
    void setE(int e, Object mutator);

    long getF();
    void setF(long f, Object mutator);

    float getG();
    void setG(float g, Object mutator);

    double getH();
    void setH(double h, Object mutator);

    EarStateList getEars(); // (optional)
    void setEars(EarStateList ears, Object mutator);

    MouthStateList getMouths();
    void setMouths(MouthStateList mouths, Object mutator);

    boolean isValid();
    boolean isValidAsEncapsulated();
    boolean equalsValue(Object obj);
    void encapsulate();
    void setEncapsulator(Object encapsulator);
    Certificate certificate();
}
