package net.sf.laja.cdd.state.animal;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface AnimalState {
    boolean getIsTerrestrial();
    void setIsTerrestrial(boolean isTerrestrial);

    boolean isValid();
    boolean isValidAsEncapsulated();
    boolean valueEquals(Object o);
    int valueHashCode();
    void encapsulate();
}
