package net.sf.laja.cdd.state.animal;

import net.sf.laja.cdd.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class AnimalValue implements AnimalElement {
    protected final AnimalState state;
    protected AnimalStateBuilder stateBuilder;

    public AnimalValue(AnimalState state) {
        this.state = state;
        state.setEncapsulator(this);
    }

    public AnimalValue(AnimalState state, AnimalStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
        state.setEncapsulator(this);
    }

    public AnimalState getState(Certificate certificate) {
        if (certificate == null) {
            throw new IllegalArgumentException("Certificate can not be null!");
        }
        return state;
    }

    public AnimalState getState(AnimalStateList stateList) {
        return state;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.valueEquals(((AnimalValue)o).state);
    }

    @Override
    public int hashCode() {
        return state.valueHashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
