package net.sf.laja.cdd.state.animal;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class AnimalStateProjection {

    AnimalStateProjection() {
    }

    public static AnimalStateProjection isTerrestrial(boolean isTerrestrial) {
        return new AnimalStateProjection();
    }
}
