package net.sf.laja.cdd.state.animal;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface AnimalStateBehaviourFactory {
    Object create(AnimalState state, Object... args);
}
