package net.sf.laja.cdd.state.hair;

import net.sf.laja.cdd.state.Certificate;

import java.util.ArrayList;
import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public final class HairStateListBuilder {
    private Object lastMutator;
    private final Certificate certificate;
    private final HairStateList states;

    public HairStateListBuilder() {
        certificate = Certificate.get(new HairStateImpl());
        states = HairStateListImpl.emptyList(certificate);
    }

    public HairStateListBuilder(HairStateList states) {
        this.states = states;
        certificate = Certificate.get(new HairStateImpl());
    }

    public HairStateList getStateList(Certificate certificate) {
        return states;
    }

    public List<HairStateBuilder> getStateBuilders() {
        List<HairStateBuilder> builders = new ArrayList<HairStateBuilder>(states.size());

        for (HairState state : states) {
            builders.add(new HairStateBuilderImpl(state));
        }
        return builders;
    }

    public void throwExceptionIfOutOfSync(Object accessor) {
        if (lastMutator != null && lastMutator != accessor) {
            throw new IllegalStateException("The state has been changed by another list. Call syncState() to synchronize the internal state with the enclosing list.");
        }
    }

    private void prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(Object mutator) {
        throwExceptionIfOutOfSync(mutator);
        this.lastMutator = mutator;
    }

    public void syncState() {
        this.lastMutator = null;
    }

    public int size() {
        return states.size();
    }

    public void clear(Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.clear();
    }

    public void add(HairStateBuilder builder) {
        states.add(builder.getHairState(certificate));
    }

    public void add(HairState state) {
        states.add(state);
    }

    public void add(HairState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(state);
    }

    public void add(int index, HairState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(index, state);
    }

    public void addAll(int index, HairStateListBuilder listBuilder, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.addAll(index, listBuilder.states);
    }

    public void set(int index, HairState state, Object accessor) {
        throwExceptionIfOutOfSync(accessor);
        states.set(index, state);
    }

    public boolean remove(HairState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        return states.remove(state);
    }

    public void remove(int index, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.remove(index);
    }

    public void retainAll(HairStateListBuilder retainStates, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "HairStateListBuilder{states=" + states + ", lastMutator.hashCode()=" + (lastMutator == null ? null : lastMutator.hashCode()) + "}";
    }
}
