package net.sf.laja.cdd.state.hair;

import net.sf.laja.cdd.state.Certificate;

import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface HairStateList extends List<HairState> {
    Certificate certificate();
    boolean isValid();
    void encapsulate();
}
