package net.sf.laja.example.computer.state;

import net.sf.laja.example.computer.state.Certificate;

import java.util.ArrayList;
import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public final class ComputerStateListBuilder {
    private Object lastMutator;
    private final Certificate certificate;
    private final ComputerStateList states;

    public ComputerStateListBuilder() {
        certificate = Certificate.get(new ComputerStateImpl());
        states = ComputerStateListImpl.emptyList(certificate);
    }

    public ComputerStateListBuilder(ComputerStateList states) {
        this.states = states;
        certificate = Certificate.get(new ComputerStateImpl());
    }

    public ComputerStateList getStateList(Certificate certificate) {
        return states;
    }

    public List<ComputerStateBuilder> getStateBuilders() {
        List<ComputerStateBuilder> builders = new ArrayList<ComputerStateBuilder>(states.size());

        for (ComputerState state : states) {
            builders.add(new ComputerStateBuilderImpl(state));
        }
        return builders;
    }

    public void throwExceptionIfOutOfSync(Object accessor) {
        if (lastMutator != null && lastMutator != accessor) {
            throw new IllegalStateException("The state has been changed by another list. Call syncState() to synchronize the internal state with the enclosing list.");
        }
    }

    private void prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(Object mutator) {
        throwExceptionIfOutOfSync(mutator);
        this.lastMutator = mutator;
    }

    public void syncState() {
        this.lastMutator = null;
    }

    public int size() {
        return states.size();
    }

    public void clear(Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.clear();
    }

    public void add(ComputerStateBuilder builder) {
        states.add(builder.getComputerState(certificate));
    }

    public void add(ComputerState state) {
        states.add(state);
    }

    public void add(ComputerState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(state);
    }

    public void add(int index, ComputerState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(index, state);
    }

    public void addAll(int index, ComputerStateListBuilder listBuilder, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.addAll(index, listBuilder.states);
    }

    public void set(int index, ComputerState state, Object accessor) {
        throwExceptionIfOutOfSync(accessor);
        states.set(index, state);
    }

    public boolean remove(ComputerState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        return states.remove(state);
    }

    public void remove(int index, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.remove(index);
    }

    public void retainAll(ComputerStateListBuilder retainStates, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "ComputerStateListBuilder{states=" + states + ", lastMutator.hashCode()=" + (lastMutator == null ? null : lastMutator.hashCode()) + "}";
    }
}
