package net.sf.laja.example.car.state;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface BusStateBehaviourFactory {
    Object create(BusState state, Object... args);
}
