package net.sf.laja.example.car.state;

import net.sf.laja.example.car.state.VehicleSizeState;
import net.sf.laja.example.car.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public interface BusState extends VehicleSizeState {
    String getName();
    void setName(String name, Object mutator);

    int getLengthInCentimeters();
    void setLengthInCentimeters(int lengthInCentimeters, Object mutator);

    int getWeightInKilograms(); // (optional)
    void setWeightInKilograms(int weightInKilograms, Object mutator);
}
