package net.sf.laja.example.car.state;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public final class BusStateSetBuilder {
    private final Certificate certificate;
    private final BusStateSet states;

    public BusStateSetBuilder() {
        certificate = Certificate.get(new BusStateImpl());
        states = BusStateHashSet.emptySet();
    }

    public BusStateSetBuilder(BusStateSet states) {
        this.states = states;
        certificate = Certificate.get(new BusStateImpl());
    }

    public BusStateSet getStateSet(Certificate certificate) {
        return states;
    }

    public List<BusStateBuilder> getStateBuilders() {
        List<BusStateBuilder> builders = new ArrayList<BusStateBuilder>(states.size());

        for (BusState state : states) {
            builders.add(new BusStateBuilderImpl(state));
        }
        return builders;
    }

    public int size() {
        return states.size();
    }

    public void clear() {
        states.clear();
    }

    public void add(BusStateBuilder builder) {
        states.add(builder.getBusState(certificate));
    }

    public void add(BusState state) {
        states.add(state);
    }

    public boolean remove(BusState state) {
        return states.remove(state);
    }

    public void remove(int index) {
        states.remove(index);
    }

    public void retainAll(BusStateSetBuilder retainStates) {
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "BusStateSetBuilder{" + states + "}";
    }
}
