package net.sf.laja.example.car.state;

import java.util.*;
import net.sf.laja.example.car.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class BusStateListImpl extends ArrayList<BusState> implements BusStateList {
    private boolean _encapsulated = false;

    public BusStateListImpl() {
    }

    public BusStateListImpl(int size) {
        super(size);
    }

    public static BusStateList emptyList() {
        return new BusStateListImpl();
    }

    public Certificate certificate() {
        return Certificate.get(this);
    }

    public boolean isValid() {
        for (BusState state : this) {
            if (!state.isValid()) {
                return false;
            }
        }
        return true;
    }

    public void encapsulate() {
        _encapsulated = true;

        for (BusState state : this) {
            state.encapsulate();
        }
    }
}
