package net.sf.laja.example.car.state;

import net.sf.laja.example.car.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public interface OwnerStateBuilder extends OwnerStateComparable {
    void withSsn(long ssn);
    void withName(String name);
    boolean isValid();
    Object as(OwnerBehaviourFactory factory, Object... args);
    OwnerState getOwnerState(net.sf.laja.example.car.state.Certificate certificate);
}
