package net.sf.laja.example.car.state;

import net.sf.laja.example.car.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class TruckValue implements TruckElement {
    protected final TruckState state;
    protected TruckStateBuilder stateBuilder;

    public TruckValue(TruckState state) {
        this.state = state;
        state.setEncapsulator(this);
    }

    public TruckValue(TruckState state, TruckStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
        state.setEncapsulator(this);
    }

    public TruckState getState(Certificate certificate) {
        if (certificate == null) {
            throw new IllegalArgumentException("Certificate can not be null!");
        }
        return state;
    }

    public TruckState getState(TruckStateList stateList) {
        if (stateList == null) {
            throw new IllegalArgumentException("TruckStateList can not be null!");
        }
        return state;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.valueEquals(((TruckValue)o).state);
    }

    @Override
    public int hashCode() {
        return state.valueHashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
