package net.sf.laja.example.car.state;

import net.sf.laja.example.car.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class TruckTypeValue implements TruckTypeElement {
    protected final TruckTypeState state;
    protected TruckTypeStateBuilder stateBuilder;

    public TruckTypeValue(TruckTypeState state) {
        this.state = state;
    }

    public TruckTypeValue(TruckTypeState state, TruckTypeStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
    }

    public TruckTypeState getState(Certificate certificate) {
        return state;
    }

    public void addToList(TruckTypeStateList stateList) {
        stateList.add(state);
    }

    public void addToList(TruckTypeStateListBuilder listBuilder) {
        listBuilder.add(state);
    }

    public void addToList(TruckTypeStateListBuilder listBuilder, Object mutator) {
        listBuilder.add(state, mutator);
    }

    public void addToList(int index, TruckTypeStateListBuilder listBuilder, Object mutator) {
        listBuilder.add(index, state, mutator);
    }

    public void setInList(int index, TruckTypeStateListBuilder listBuilder, Object accessor) {
        listBuilder.set(index, state, accessor);
    }

    public boolean removeFromList(TruckTypeStateListBuilder listBuilder, Object mutator) {
        return listBuilder.remove(state, mutator);
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.valueEquals(((TruckTypeValue)o).state);
    }

    @Override
    public int hashCode() {
        return state.valueHashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
