package net.sf.laja.example.car.state;

import net.sf.laja.example.car.state.Certificate;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class TruckValue implements TruckElement {
    protected final TruckState state;
    protected TruckStateBuilder stateBuilder;

    public TruckValue(TruckState state) {
        this.state = state;
    }

    public TruckValue(TruckState state, TruckStateBuilder stateBuilder) {
        this.state = state;
        this.stateBuilder = stateBuilder;
    }

    public boolean isStateInSync() {
        return true;
    }

    public boolean syncState() {
        return false;
    }

    public boolean contains(TruckStateList stateList) {
        return stateList.contains(state);
    }

    public TruckState getState(Certificate certificate) {
        return state;
    }

    public void addToList(TruckStateList stateList) {
        stateList.add(state);
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;

        return state.valueEquals(((TruckValue)o).state);
    }

    @Override
    public int hashCode() {
        return state.valueHashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + state;
    }
}
