package net.sf.laja.example.car.state;

import net.sf.laja.example.car.state.Certificate;

import java.util.ArrayList;
import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public final class VehicleSizeStateListBuilder {
    private Object lastMutator;
    private final Certificate certificate;
    private final VehicleSizeStateList states;

    public VehicleSizeStateListBuilder() {
        certificate = Certificate.get(new VehicleSizeStateImpl());
        states = VehicleSizeStateListImpl.emptyList(certificate);
    }

    public VehicleSizeStateListBuilder(VehicleSizeStateList states) {
        this.states = states;
        certificate = Certificate.get(new VehicleSizeStateImpl());
    }

    public VehicleSizeStateList getStateList(Certificate certificate) {
        return states;
    }

    public List<VehicleSizeStateBuilder> getStateBuilders() {
        List<VehicleSizeStateBuilder> builders = new ArrayList<VehicleSizeStateBuilder>(states.size());

        for (VehicleSizeState state : states) {
            builders.add(new VehicleSizeStateBuilderImpl(state));
        }
        return builders;
    }

    public void throwExceptionIfOutOfSync(Object accessor) {
        if (lastMutator != null && lastMutator != accessor) {
            throw new IllegalStateException("The state has been changed by another list. Call syncState() to synchronize the internal state with the enclosing list.");
        }
    }

    private void prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(Object mutator) {
        throwExceptionIfOutOfSync(mutator);
        this.lastMutator = mutator;
    }

    public void syncState() {
        this.lastMutator = null;
    }

    public int size() {
        return states.size();
    }

    public void clear(Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.clear();
    }

    public void add(VehicleSizeStateBuilder builder) {
        states.add(builder.getVehicleSizeState(certificate));
    }

    public void add(VehicleSizeState state) {
        states.add(state);
    }

    public void add(VehicleSizeState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(state);
    }

    public void add(int index, VehicleSizeState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(index, state);
    }

    public void addAll(int index, VehicleSizeStateListBuilder listBuilder, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.addAll(index, listBuilder.states);
    }

    public void set(int index, VehicleSizeState state, Object accessor) {
        throwExceptionIfOutOfSync(accessor);
        states.set(index, state);
    }

    public boolean remove(VehicleSizeState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        return states.remove(state);
    }

    public void remove(int index, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.remove(index);
    }

    public void retainAll(VehicleSizeStateListBuilder retainStates, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "VehicleSizeStateListBuilder{states=" + states + ", lastMutator.hashCode()=" + (lastMutator == null ? null : lastMutator.hashCode()) + "}";
    }
}
