package net.sf.laja.example.account.state;

import net.sf.laja.example.account.state.Certificate;

import java.util.ArrayList;
import java.util.List;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public final class AccountStateListBuilder {
    private Object lastMutator;
    private final Certificate certificate;
    private final AccountStateList states;

    public AccountStateListBuilder() {
        certificate = Certificate.get(new AccountStateImpl());
        states = AccountStateListImpl.emptyList(certificate);
    }

    public AccountStateListBuilder(AccountStateList states) {
        this.states = states;
        certificate = Certificate.get(new AccountStateImpl());
    }

    public AccountStateList getStateList(Certificate certificate) {
        return states;
    }

    public List<AccountStateBuilder> getStateBuilders() {
        List<AccountStateBuilder> builders = new ArrayList<AccountStateBuilder>(states.size());

        for (AccountState state : states) {
            builders.add(new AccountStateBuilderImpl(state));
        }
        return builders;
    }

    public void throwExceptionIfOutOfSync(Object accessor) {
        if (lastMutator != null && lastMutator != accessor) {
            throw new IllegalStateException("The state has been changed by another list. Call syncState() to synchronize the internal state with the enclosing list.");
        }
    }

    private void prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(Object mutator) {
        throwExceptionIfOutOfSync(mutator);
        this.lastMutator = mutator;
    }

    public void syncState() {
        this.lastMutator = null;
    }

    public int size() {
        return states.size();
    }

    public void clear(Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.clear();
    }

    public void add(AccountStateBuilder builder) {
        states.add(builder.getAccountState(certificate));
    }

    public void add(AccountState state) {
        states.add(state);
    }

    public void add(AccountState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(state);
    }

    public void add(int index, AccountState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.add(index, state);
    }

    public void addAll(int index, AccountStateListBuilder listBuilder, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.addAll(index, listBuilder.states);
    }

    public void set(int index, AccountState state, Object accessor) {
        throwExceptionIfOutOfSync(accessor);
        states.set(index, state);
    }

    public boolean remove(AccountState state, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        return states.remove(state);
    }

    public void remove(int index, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.remove(index);
    }

    public void retainAll(AccountStateListBuilder retainStates, Object mutator) {
        prepareAddOrRemoveElementAndThrowExceptionIfOutOfSync(mutator);
        states.retainAll(retainStates.states);
    }

    @Override
    public String toString() {
        return "AccountStateListBuilder{states=" + states + ", lastMutator.hashCode()=" + (lastMutator == null ? null : lastMutator.hashCode()) + "}";
    }
}
