package net.sf.laja.example.person.behaviour;

import net.sf.laja.example.person.state.*;
import net.sf.laja.example.person.behaviour.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class BodyMassIndexHashSet implements BodyMassIndexSet, RandomAccess, Cloneable, java.io.Serializable {
    protected BmiStateList stateSet;
    protected final Set<BodyMassIndex> set;

    public BodyMassIndexHashSet(BodyMassIndex... array) {
        this.set = new HashSet<BodyMassIndex>();
        this.set.addAll(Arrays.asList(array));
    }

    public BodyMassIndexHashSet(Collection<BodyMassIndex> collection) {
        this.set = new HashSet<BodyMassIndex>();
        this.set.addAll(collection);
    }

    public BodyMassIndexHashSet(BmiStateList stateSet) {
        this.stateSet = stateSet;
        this.stateSet.encapsulate(this);
        Set<BodyMassIndex> elements = new HashSet<BodyMassIndex>(stateSet.size());

        for (BmiState state : stateSet) {
            BmiStateBuilder builder = new BmiStateBuilderImpl(state);
            BodyMassIndex entry = (BodyMassIndex) builder.as(new BodyMassIndexFactory.BodyMassIndexFactory_(builder));
            elements.add(entry);
        }
        this.set = new StateInSyncSet(stateSet, elements);
    }

    public class StateInSyncSet extends HashSet<BodyMassIndex> {
        private final BmiStateList stateSet;

        public StateInSyncSet(BmiStateList stateSet, Set<BodyMassIndex> elements) {
            this.stateSet = stateSet;
            super.addAll(elements);
        }

        @Override
        public boolean add(BodyMassIndex element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(BodyMassIndexHashSet.this);
            stateSet.add(element.getState(stateSet.certificate()));
            return super.add(element);
        }

        @Override
        public boolean addAll(Collection<? extends BodyMassIndex> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(BodyMassIndexHashSet.this);
            boolean modified = super.addAll(collection);

            for (BodyMassIndex element : collection) {
                stateSet.add(element.getState(stateSet.certificate()));
            }
            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(BodyMassIndexHashSet.this);
            if (!(element instanceof BodyMassIndex)) {
                return false;
            }
            stateSet.remove(((BodyMassIndex) element).getState(stateSet.certificate()));

            return super.remove(element);
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(BodyMassIndexHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof BodyMassIndex) {
                    elements.add(element);
                    states.add(((BodyMassIndex)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateSet.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(BodyMassIndexHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof BodyMassIndex) {
                    elements.add(element);
                    states.add(((BodyMassIndex)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateSet.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateSet.throwExceptionIfNotEncapsulatedBy(BodyMassIndexHashSet.this);
            stateSet.clear();
            super.clear();
        }
    }

    public int size() {
        return set.size();
    }

    public boolean isEmpty() {
        return set.isEmpty();
    }

    public boolean contains(Object element) {
        return set.contains(element);
    }

    public Iterator<BodyMassIndex> iterator() {
        return set.iterator();
    }

    public Object[] toArray() {
        return set.toArray();
    }

    public <BodyMassIndex> BodyMassIndex[] toArray(BodyMassIndex[] array) {
        return set.toArray(array);
    }

    public boolean add(BodyMassIndex element) {
        return set.add(element);
    }

    public boolean addAll(Collection<? extends BodyMassIndex> collection) {
        return set.addAll(collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof BodyMassIndex)) {
            return false;
        }
        return set.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return set.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return set.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return set.retainAll(collection);
    }

    public void clear() {
        set.clear();
    }

    @Override
    public boolean equals(Object o) {
        return set.equals(o);
    }

    @Override
    public int hashCode() {
        return set.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + set + '}';
    }
}
