package net.sf.laja.example.account.behaviour;

import net.sf.laja.example.account.state.*;
import net.sf.laja.example.account.behaviour.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.sf.net
 */
public class TestAccountArrayList implements TestAccountList, RandomAccess, Cloneable, java.io.Serializable {
    protected AccountStateList stateList;
    protected final List<TestAccount> list;

    public TestAccountArrayList(TestAccount... list) {
        this.list = new ArrayList<TestAccount>();
        this.list.addAll(Arrays.asList(list));
    }

    public TestAccountArrayList(Collection<TestAccount> list) {
        this.list = new ArrayList<TestAccount>();
        this.list.addAll(list);
    }

    public TestAccountArrayList(AccountStateList stateList) {
        this.stateList = stateList;
        this.stateList.encapsulate(this);
        List<TestAccount> elements = new ArrayList<TestAccount>(stateList.size());

        for (AccountState state : stateList) {
            AccountStateBuilder builder = new AccountStateBuilderImpl(state);
            TestAccount entry = (TestAccount) builder.as(new TestAccountFactory.TestAccountFactory_(builder));
            elements.add(entry);
        }
        this.list = new StateInSyncList(stateList, elements);
    }

    public SourceAccountArrayList asSourceAccountList() {
        List<SourceAccount> result = new ArrayList<SourceAccount>();
        for (TestAccount entry : list) {
            result.add(entry.asSourceAccount());
        }
        return new SourceAccountArrayList(result);
    }

    public DestinationAccountArrayList asDestinationAccountList() {
        List<DestinationAccount> result = new ArrayList<DestinationAccount>();
        for (TestAccount entry : list) {
            result.add(entry.asDestinationAccount());
        }
        return new DestinationAccountArrayList(result);
    }

    public class StateInSyncList extends ArrayList<TestAccount> {
        private final AccountStateList stateList;

        public StateInSyncList(AccountStateList stateList, List<TestAccount> elements) {
            this.stateList = stateList;
            super.addAll(elements);
        }

        @Override
        public boolean add(TestAccount element) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            stateList.add(element.getState(stateList));
            return super.add(element);
        }

        @Override
        public void add(int index, TestAccount element) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            stateList.add(index, element.getState(stateList));
            super.add(index, element);
        }

        @Override
        public boolean addAll(Collection<? extends TestAccount> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            boolean modified = super.addAll(collection);

            for (TestAccount element : collection) {
                stateList.add(element.getState(stateList));
            }
            return modified;
        }

        @Override
        public boolean addAll(int index, Collection<? extends TestAccount> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            boolean modified = super.addAll(index, collection);

            List elements = new ArrayList(collection.size());
            for (TestAccount element : collection) {
                elements.add(element.getState(stateList));
            }
            stateList.addAll(index, elements);

            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            if (!(element instanceof TestAccount)) {
                return false;
            }
            stateList.remove(((TestAccount) element).getState(stateList));

            return super.remove(element);
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof TestAccount) {
                    elements.add(element);
                    states.add(((TestAccount)element).getState(stateList));
                }
            }
            boolean modified = super.removeAll(elements);
            stateList.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof TestAccount) {
                    elements.add(element);
                    states.add(((TestAccount)element).getState(stateList));
                }
            }
            boolean modified = super.retainAll(elements);
            stateList.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            stateList.clear();
            super.clear();
        }

        @Override
        public TestAccount set(int index, TestAccount element) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            stateList.set(index, element.getState(stateList));
            return super.set(index, element);
        }

        @Override
        public TestAccount remove(int index) {
            stateList.throwExceptionIfNotEncapsulatedBy(TestAccountArrayList.this);
            stateList.remove(index);
            return super.remove(index);
        }
    }

    public int size() {
        return list.size();
    }

    public boolean isEmpty() {
        return list.isEmpty();
    }

    public boolean contains(Object element) {
        return list.contains(element);
    }

    public Iterator<TestAccount> iterator() {
        return list.iterator();
    }

    public Object[] toArray() {
        return list.toArray();
    }

    public <TestAccount> TestAccount[] toArray(TestAccount[] array) {
        return list.toArray(array);
    }

    public boolean add(TestAccount element) {
        return list.add(element);
    }

    public void add(int index, TestAccount element) {
        list.add(index, element);
    }

    public boolean addAll(Collection<? extends TestAccount> collection) {
        return list.addAll(collection);
    }

    public boolean addAll(int index, Collection<? extends TestAccount> collection) {
        return list.addAll(index, collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof TestAccount)) {
            return false;
        }
        return list.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return list.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return list.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return list.retainAll(collection);
    }

    public void clear() {
        list.clear();
    }

    public TestAccount get(int index) {
        return list.get(index);
    }

    public TestAccount set(int index, TestAccount element) {
        return list.set(index, element);
    }

    public TestAccount remove(int index) {
        return list.remove(index);
    }

    public int indexOf(Object element) {
        return list.indexOf(element);
    }

    public int lastIndexOf(Object element) {
        return list.lastIndexOf(element);
    }

    public ListIterator<TestAccount> listIterator() {
        return list.listIterator();
    }

    public ListIterator<TestAccount> listIterator(int index) {
        return list.listIterator(index);
    }

    public List<TestAccount> subList(int fromIndex, int toIndex) {
        return list.subList(fromIndex, toIndex);
    }

    @Override
    public boolean equals(Object o) {
        return list.equals(o);
    }

    @Override
    public int hashCode() {
        return list.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + list + '}';
    }
}
