package net.sf.laja.example.car.behaviour;

import net.sf.laja.example.car.state.*;
import net.sf.laja.example.car.behaviour.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class TruckTypeHashSet implements TruckTypeSet, RandomAccess, Cloneable, java.io.Serializable {
    protected TruckTypeStateList stateSet;
    protected final Set<TruckType> set;

    public TruckTypeHashSet(TruckType... array) {
        this.set = new HashSet<TruckType>();
        this.set.addAll(Arrays.asList(array));
    }

    public TruckTypeHashSet(Collection<TruckType> collection) {
        this.set = new HashSet<TruckType>();
        this.set.addAll(collection);
    }

    public TruckTypeHashSet(TruckTypeStateList stateSet) {
        this.stateSet = stateSet;
        this.stateSet.encapsulate(this);
        Set<TruckType> elements = new HashSet<TruckType>(stateSet.size());

        for (TruckTypeState state : stateSet) {
            TruckTypeStateBuilder builder = new TruckTypeStateBuilderImpl(state);
            TruckType entry = (TruckType) builder.as(new TruckTypeFactory.TruckTypeFactory_(builder));
            elements.add(entry);
        }
        this.set = new StateInSyncSet(stateSet, elements);
    }

    public class StateInSyncSet extends HashSet<TruckType> {
        private final TruckTypeStateList stateSet;

        public StateInSyncSet(TruckTypeStateList stateSet, Set<TruckType> elements) {
            this.stateSet = stateSet;
            super.addAll(elements);
        }

        @Override
        public boolean add(TruckType element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(TruckTypeHashSet.this);
            stateSet.add(element.getState(stateSet.certificate()));
            return super.add(element);
        }

        @Override
        public boolean addAll(Collection<? extends TruckType> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(TruckTypeHashSet.this);
            boolean modified = super.addAll(collection);

            for (TruckType element : collection) {
                stateSet.add(element.getState(stateSet.certificate()));
            }
            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(TruckTypeHashSet.this);
            if (!(element instanceof TruckType)) {
                return false;
            }
            stateSet.remove(((TruckType) element).getState(stateSet.certificate()));

            return super.remove(element);
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(TruckTypeHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof TruckType) {
                    elements.add(element);
                    states.add(((TruckType)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateSet.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(TruckTypeHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof TruckType) {
                    elements.add(element);
                    states.add(((TruckType)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateSet.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateSet.throwExceptionIfNotEncapsulatedBy(TruckTypeHashSet.this);
            stateSet.clear();
            super.clear();
        }
    }

    public int size() {
        return set.size();
    }

    public boolean isEmpty() {
        return set.isEmpty();
    }

    public boolean contains(Object element) {
        return set.contains(element);
    }

    public Iterator<TruckType> iterator() {
        return set.iterator();
    }

    public Object[] toArray() {
        return set.toArray();
    }

    public <TruckType> TruckType[] toArray(TruckType[] array) {
        return set.toArray(array);
    }

    public boolean add(TruckType element) {
        return set.add(element);
    }

    public boolean addAll(Collection<? extends TruckType> collection) {
        return set.addAll(collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof TruckType)) {
            return false;
        }
        return set.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return set.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return set.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return set.retainAll(collection);
    }

    public void clear() {
        set.clear();
    }

    @Override
    public boolean equals(Object o) {
        return set.equals(o);
    }

    @Override
    public int hashCode() {
        return set.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + set + '}';
    }
}
