package net.sf.laja.example.car.behaviour;

import net.sf.laja.example.car.state.*;
import net.sf.laja.example.car.behaviour.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class VehicleArrayList implements VehicleList, RandomAccess, Cloneable, java.io.Serializable {
    protected VehicleStateList stateList;
    protected final List<Vehicle> list;

    public VehicleArrayList(Vehicle... array) {
        this.list = new ArrayList<Vehicle>();
        this.list.addAll(Arrays.asList(array));
    }

    public VehicleArrayList(Collection<Vehicle> collection) {
        this.list = new ArrayList<Vehicle>();
        this.list.addAll(collection);
    }

    public VehicleArrayList(VehicleStateList stateList) {
        this.stateList = stateList;
        this.stateList.encapsulate(this);
        List<Vehicle> elements = new ArrayList<Vehicle>(stateList.size());

        for (VehicleState state : stateList) {
            VehicleStateBuilder builder = new VehicleStateBuilderImpl(state);
            Vehicle entry = (Vehicle) builder.as(new VehicleFactory.VehicleFactory_(builder));
            elements.add(entry);
        }
        this.list = new StateInSyncList(stateList, elements);
    }

    public class StateInSyncList extends ArrayList<Vehicle> {
        private final VehicleStateList stateList;

        public StateInSyncList(VehicleStateList stateList, List<Vehicle> elements) {
            this.stateList = stateList;
            super.addAll(elements);
        }

        @Override
        public boolean add(Vehicle element) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            stateList.add(element.getState(stateList.certificate()));
            return super.add(element);
        }

        @Override
        public void add(int index, Vehicle element) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            stateList.add(index, element.getState(stateList.certificate()));
            super.add(index, element);
        }

        @Override
        public boolean addAll(Collection<? extends Vehicle> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            boolean modified = super.addAll(collection);

            for (Vehicle element : collection) {
                stateList.add(element.getState(stateList.certificate()));
            }
            return modified;
        }

        @Override
        public boolean addAll(int index, Collection<? extends Vehicle> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            boolean modified = super.addAll(index, collection);

            List elements = new ArrayList(collection.size());
            for (Vehicle element : collection) {
                elements.add(element.getState(stateList.certificate()));
            }
            stateList.addAll(index, elements);

            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            if (!(element instanceof Vehicle)) {
                return false;
            }
            stateList.remove(((Vehicle) element).getState(stateList.certificate()));

            return super.remove(element);
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof Vehicle) {
                    elements.add(element);
                    states.add(((Vehicle)element).getState(stateList.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateList.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof Vehicle) {
                    elements.add(element);
                    states.add(((Vehicle)element).getState(stateList.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateList.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            stateList.clear();
            super.clear();
        }

        @Override
        public Vehicle set(int index, Vehicle element) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            stateList.set(index, element.getState(stateList.certificate()));
            return super.set(index, element);
        }

        @Override
        public Vehicle remove(int index) {
            stateList.throwExceptionIfNotEncapsulatedBy(VehicleArrayList.this);
            stateList.remove(index);
            return super.remove(index);
        }
    }

    public int size() {
        return list.size();
    }

    public boolean isEmpty() {
        return list.isEmpty();
    }

    public boolean contains(Object element) {
        return list.contains(element);
    }

    public Iterator<Vehicle> iterator() {
        return list.iterator();
    }

    public Object[] toArray() {
        return list.toArray();
    }

    public <Vehicle> Vehicle[] toArray(Vehicle[] array) {
        return list.toArray(array);
    }

    public boolean add(Vehicle element) {
        return list.add(element);
    }

    public void add(int index, Vehicle element) {
        list.add(index, element);
    }

    public boolean addAll(Collection<? extends Vehicle> collection) {
        return list.addAll(collection);
    }

    public boolean addAll(int index, Collection<? extends Vehicle> collection) {
        return list.addAll(index, collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof Vehicle)) {
            return false;
        }
        return list.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return list.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return list.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return list.retainAll(collection);
    }

    public void clear() {
        list.clear();
    }

    public Vehicle get(int index) {
        return list.get(index);
    }

    public Vehicle set(int index, Vehicle element) {
        return list.set(index, element);
    }

    public Vehicle remove(int index) {
        return list.remove(index);
    }

    public int indexOf(Object element) {
        return list.indexOf(element);
    }

    public int lastIndexOf(Object element) {
        return list.lastIndexOf(element);
    }

    public ListIterator<Vehicle> listIterator() {
        return list.listIterator();
    }

    public ListIterator<Vehicle> listIterator(int index) {
        return list.listIterator(index);
    }

    public List<Vehicle> subList(int fromIndex, int toIndex) {
        return list.subList(fromIndex, toIndex);
    }

    @Override
    public boolean equals(Object o) {
        return list.equals(o);
    }

    @Override
    public int hashCode() {
        return list.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + list + '}';
    }
}
