package net.sf.laja.example.car.behaviour;

import net.sf.laja.example.car.state.*;
import net.sf.laja.example.car.behaviour.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class VehicleSizeHashSet implements VehicleSizeSet, RandomAccess, Cloneable, java.io.Serializable {
    protected VehicleSizeStateSet stateSet;
    protected final Set<VehicleSize> set;

    public VehicleSizeHashSet(VehicleSize... array) {
        this.set = new HashSet<VehicleSize>();
        this.set.addAll(Arrays.asList(array));
    }

    public VehicleSizeHashSet(Collection<VehicleSize> collection) {
        this.set = new HashSet<VehicleSize>();
        this.set.addAll(collection);
    }

    public VehicleSizeHashSet(VehicleSizeStateSet stateSet) {
        this.stateSet = stateSet;
        this.stateSet.encapsulate(this);
        Set<VehicleSize> elements = new HashSet<VehicleSize>(stateSet.size());

        for (VehicleSizeState state : stateSet) {
            VehicleSizeStateBuilder builder = new VehicleSizeStateBuilderImpl(state);
            VehicleSize entry = (VehicleSize) builder.as(new VehicleSizeFactory.VehicleSizeFactory_(builder));
            elements.add(entry);
        }
        this.set = new StateInSyncSet(stateSet, elements);
    }

    public class StateInSyncSet extends HashSet<VehicleSize> {
        private VehicleSizeStateSet stateSet;

        public StateInSyncSet(VehicleSizeStateSet stateSet, Set<VehicleSize> elements) {
            this.stateSet = stateSet;
            this.stateSet.clear();
            super.addAll(elements);
        }

        @Override
        public boolean add(VehicleSize element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(VehicleSizeHashSet.this);
            stateSet.add(element.getState(stateSet.certificate()));
            return super.add(element);
        }

        @Override
        public boolean addAll(Collection<? extends VehicleSize> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(VehicleSizeHashSet.this);
            boolean modified = super.addAll(collection);

            for (VehicleSize element : collection) {
                stateSet.add(element.getState(stateSet.certificate()));
            }
            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateSet.throwExceptionIfNotEncapsulatedBy(VehicleSizeHashSet.this);
            if (!(element instanceof VehicleSize)) {
                return false;
            }
            boolean removedState = stateSet.remove(((VehicleSize) element).getState(stateSet.certificate()));
            boolean removedElement = super.remove(element);

            if (removedState != removedElement) {
                throw new IllegalStateException("The state and behaviour is out of sync. Please report this bug to the Laja project!");
            }
            return removedElement;
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(VehicleSizeHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof VehicleSize) {
                    elements.add(element);
                    states.add(((VehicleSize)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateSet.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateSet.throwExceptionIfNotEncapsulatedBy(VehicleSizeHashSet.this);
            Set states = new HashSet(collection.size());
            Set elements = new HashSet(collection.size());
            for (Object element : collection) {
                if (element instanceof VehicleSize) {
                    elements.add(element);
                    states.add(((VehicleSize)element).getState(stateSet.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateSet.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateSet.throwExceptionIfNotEncapsulatedBy(VehicleSizeHashSet.this);
            stateSet.clear();
            super.clear();
        }
    }

    public int size() {
        return set.size();
    }

    public boolean isEmpty() {
        return set.isEmpty();
    }

    public boolean contains(Object element) {
        return set.contains(element);
    }

    public Iterator<VehicleSize> iterator() {
        return set.iterator();
    }

    public Object[] toArray() {
        return set.toArray();
    }

    public <VehicleSize> VehicleSize[] toArray(VehicleSize[] array) {
        return set.toArray(array);
    }

    public boolean add(VehicleSize element) {
        return set.add(element);
    }

    public boolean addAll(Collection<? extends VehicleSize> collection) {
        return set.addAll(collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof VehicleSize)) {
            return false;
        }
        return set.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return set.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return set.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return set.retainAll(collection);
    }

    public void clear() {
        set.clear();
    }

    @Override
    public boolean equals(Object o) {
        return set.equals(o);
    }

    @Override
    public int hashCode() {
        return set.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + set + '}';
    }
}
