package net.sf.laja.cdd.state;

import net.sf.laja.cdd.state.forehead.ForeheadStateImpl;
import net.sf.laja.cdd.state.forehead.ForeheadStateListImpl;
import net.sf.laja.cdd.state.forehead.ForeheadStateBuilderImpl;
import net.sf.laja.cdd.state.eye.EyeStateImpl;
import net.sf.laja.cdd.state.eye.EyeStateListImpl;
import net.sf.laja.cdd.state.eye.EyeStateBuilderImpl;
import net.sf.laja.cdd.state.head.HeadStateImpl;
import net.sf.laja.cdd.state.head.HeadStateListImpl;
import net.sf.laja.cdd.state.head.HeadStateBuilderImpl;
import net.sf.laja.cdd.state.monster.MonsterStateImpl;
import net.sf.laja.cdd.state.monster.MonsterStateListImpl;
import net.sf.laja.cdd.state.monster.MonsterStateBuilderImpl;
import net.sf.laja.cdd.state.animal.AnimalStateImpl;
import net.sf.laja.cdd.state.animal.AnimalStateListImpl;
import net.sf.laja.cdd.state.animal.AnimalStateBuilderImpl;
import net.sf.laja.cdd.state.fleck.FleckStateImpl;
import net.sf.laja.cdd.state.fleck.FleckStateListImpl;
import net.sf.laja.cdd.state.fleck.FleckStateBuilderImpl;
import net.sf.laja.cdd.state.hand.HandStateImpl;
import net.sf.laja.cdd.state.hand.HandStateListImpl;
import net.sf.laja.cdd.state.hand.HandStateBuilderImpl;
import net.sf.laja.cdd.state.arm.ArmStateImpl;
import net.sf.laja.cdd.state.arm.ArmStateListImpl;
import net.sf.laja.cdd.state.arm.ArmStateBuilderImpl;
import net.sf.laja.cdd.state.ear.EarStateImpl;
import net.sf.laja.cdd.state.ear.EarStateListImpl;
import net.sf.laja.cdd.state.ear.EarStateBuilderImpl;
import net.sf.laja.cdd.state.terrestrial.TerrestrialStateImpl;
import net.sf.laja.cdd.state.terrestrial.TerrestrialStateListImpl;
import net.sf.laja.cdd.state.terrestrial.TerrestrialStateBuilderImpl;
import net.sf.laja.cdd.state.hair.HairStateImpl;
import net.sf.laja.cdd.state.hair.HairStateListImpl;
import net.sf.laja.cdd.state.hair.HairStateBuilderImpl;
import net.sf.laja.cdd.state.brow.BrowStateImpl;
import net.sf.laja.cdd.state.brow.BrowStateListImpl;
import net.sf.laja.cdd.state.brow.BrowStateBuilderImpl;
import net.sf.laja.cdd.state.leg.LegStateImpl;
import net.sf.laja.cdd.state.leg.LegStateListImpl;
import net.sf.laja.cdd.state.leg.LegStateBuilderImpl;
import net.sf.laja.cdd.state.nose.NoseStateImpl;
import net.sf.laja.cdd.state.nose.NoseStateListImpl;
import net.sf.laja.cdd.state.nose.NoseStateBuilderImpl;
import net.sf.laja.cdd.state.mouth.MouthStateImpl;
import net.sf.laja.cdd.state.mouth.MouthStateListImpl;
import net.sf.laja.cdd.state.mouth.MouthStateBuilderImpl;

/**
 * Code generated by Laja - Do not change!
 * Version: laja2-006
 *
 *   http://laja.sf.net
 */
public class Certificate {
    Certificate() {
    }

    public static Certificate get(ForeheadStateImpl state) { return new Certificate(); }
    public static Certificate get(ForeheadStateListImpl state) { return new Certificate(); }
    public static Certificate get(ForeheadStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(EyeStateImpl state) { return new Certificate(); }
    public static Certificate get(EyeStateListImpl state) { return new Certificate(); }
    public static Certificate get(EyeStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(HeadStateImpl state) { return new Certificate(); }
    public static Certificate get(HeadStateListImpl state) { return new Certificate(); }
    public static Certificate get(HeadStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(MonsterStateImpl state) { return new Certificate(); }
    public static Certificate get(MonsterStateListImpl state) { return new Certificate(); }
    public static Certificate get(MonsterStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(AnimalStateImpl state) { return new Certificate(); }
    public static Certificate get(AnimalStateListImpl state) { return new Certificate(); }
    public static Certificate get(AnimalStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(FleckStateImpl state) { return new Certificate(); }
    public static Certificate get(FleckStateListImpl state) { return new Certificate(); }
    public static Certificate get(FleckStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(HandStateImpl state) { return new Certificate(); }
    public static Certificate get(HandStateListImpl state) { return new Certificate(); }
    public static Certificate get(HandStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(ArmStateImpl state) { return new Certificate(); }
    public static Certificate get(ArmStateListImpl state) { return new Certificate(); }
    public static Certificate get(ArmStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(EarStateImpl state) { return new Certificate(); }
    public static Certificate get(EarStateListImpl state) { return new Certificate(); }
    public static Certificate get(EarStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(TerrestrialStateImpl state) { return new Certificate(); }
    public static Certificate get(TerrestrialStateListImpl state) { return new Certificate(); }
    public static Certificate get(TerrestrialStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(HairStateImpl state) { return new Certificate(); }
    public static Certificate get(HairStateListImpl state) { return new Certificate(); }
    public static Certificate get(HairStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(BrowStateImpl state) { return new Certificate(); }
    public static Certificate get(BrowStateListImpl state) { return new Certificate(); }
    public static Certificate get(BrowStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(LegStateImpl state) { return new Certificate(); }
    public static Certificate get(LegStateListImpl state) { return new Certificate(); }
    public static Certificate get(LegStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(NoseStateImpl state) { return new Certificate(); }
    public static Certificate get(NoseStateListImpl state) { return new Certificate(); }
    public static Certificate get(NoseStateBuilderImpl state) { return new Certificate(); }

    public static Certificate get(MouthStateImpl state) { return new Certificate(); }
    public static Certificate get(MouthStateListImpl state) { return new Certificate(); }
    public static Certificate get(MouthStateBuilderImpl state) { return new Certificate(); }
}
