package net.sf.laja.cdd.behaviour.nail;

import net.sf.laja.cdd.state.nail.*;
import net.sf.laja.cdd.behaviour.nail.*;
import java.util.*;

/**
 * Code generated by Laja - Do not change!
 *
 *   http://laja.tengstrand.nu
 */
public class NailArrayList implements NailList, RandomAccess, Cloneable, java.io.Serializable {
    protected NailStateList stateList;
    protected final List<Nail> list;

    public NailArrayList(Nail... array) {
        this.list = new ArrayList<Nail>();
        this.list.addAll(Arrays.asList(array));
    }

    public NailArrayList(Collection<Nail> collection) {
        this.list = new ArrayList<Nail>();
        this.list.addAll(collection);
    }

    public NailArrayList(NailStateList stateList) {
        this.stateList = stateList;
        this.stateList.encapsulate(this);
        List<Nail> elements = new ArrayList<Nail>(stateList.size());

        for (NailState state : stateList) {
            NailStateBuilder builder = new NailStateBuilderImpl(state);
            Nail entry = (Nail) builder.as(new NailFactory.NailFactory_());
            elements.add(entry);
        }
        this.list = new StateInSyncList(stateList, elements);
    }

    public class StateInSyncList extends ArrayList<Nail> {
        private final NailStateList stateList;

        public StateInSyncList(NailStateList stateList, List<Nail> elements) {
            this.stateList = stateList;
            super.addAll(elements);
        }

        @Override
        public boolean add(Nail element) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            stateList.add(element.getState(stateList.certificate()));
            return super.add(element);
        }

        @Override
        public void add(int index, Nail element) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            stateList.add(index, element.getState(stateList.certificate()));
            super.add(index, element);
        }

        @Override
        public boolean addAll(Collection<? extends Nail> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            boolean modified = super.addAll(collection);

            for (Nail element : collection) {
                stateList.add(element.getState(stateList.certificate()));
            }
            return modified;
        }

        @Override
        public boolean addAll(int index, Collection<? extends Nail> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            boolean modified = super.addAll(index, collection);

            List elements = new ArrayList(collection.size());
            for (Nail element : collection) {
                elements.add(element.getState(stateList.certificate()));
            }
            stateList.addAll(index, elements);

            return modified;
        }

        @Override
        public boolean remove(Object element) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            if (!(element instanceof Nail)) {
                return false;
            }
            stateList.remove(((Nail) element).getState(stateList.certificate()));

            return super.remove(element);
        }

        @Override
        public boolean removeAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof Nail) {
                    elements.add(element);
                    states.add(((Nail)element).getState(stateList.certificate()));
                }
            }
            boolean modified = super.removeAll(elements);
            stateList.removeAll(states);

            return modified;
        }

        @Override
        public boolean retainAll(Collection<?> collection) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            List states = new ArrayList(collection.size());
            List elements = new ArrayList(collection.size());
            for (Object element : collection) {
                if (element instanceof Nail) {
                    elements.add(element);
                    states.add(((Nail)element).getState(stateList.certificate()));
                }
            }
            boolean modified = super.retainAll(elements);
            stateList.retainAll(states);

            return modified;
        }

        @Override
        public void clear() {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            stateList.clear();
            super.clear();
        }

        @Override
        public Nail set(int index, Nail element) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            stateList.set(index, element.getState(stateList.certificate()));
            return super.set(index, element);
        }

        @Override
        public Nail remove(int index) {
            stateList.throwExceptionIfNotEncapsulatedBy(NailArrayList.this);
            stateList.remove(index);
            return super.remove(index);
        }
    }

    public int size() {
        return list.size();
    }

    public boolean isEmpty() {
        return list.isEmpty();
    }

    public boolean contains(Object element) {
        return list.contains(element);
    }

    public Iterator<Nail> iterator() {
        return list.iterator();
    }

    public Object[] toArray() {
        return list.toArray();
    }

    public <Nail> Nail[] toArray(Nail[] array) {
        return list.toArray(array);
    }

    public boolean add(Nail element) {
        return list.add(element);
    }

    public void add(int index, Nail element) {
        list.add(index, element);
    }

    public boolean addAll(Collection<? extends Nail> collection) {
        return list.addAll(collection);
    }

    public boolean addAll(int index, Collection<? extends Nail> collection) {
        return list.addAll(index, collection);
    }

    public boolean remove(Object element) {
        if (!(element instanceof Nail)) {
            return false;
        }
        return list.remove(element);
    }

    public boolean containsAll(Collection<?> collection) {
        return list.containsAll(collection);
    }

    public boolean removeAll(Collection<?> collection) {
        return list.removeAll(collection);
    }

    public boolean retainAll(Collection<?> collection) {
        return list.retainAll(collection);
    }

    public void clear() {
        list.clear();
    }

    public Nail get(int index) {
        return list.get(index);
    }

    public Nail set(int index, Nail element) {
        return list.set(index, element);
    }

    public Nail remove(int index) {
        return list.remove(index);
    }

    public int indexOf(Object element) {
        return list.indexOf(element);
    }

    public int lastIndexOf(Object element) {
        return list.lastIndexOf(element);
    }

    public ListIterator<Nail> listIterator() {
        return list.listIterator();
    }

    public ListIterator<Nail> listIterator(int index) {
        return list.listIterator(index);
    }

    public List<Nail> subList(int fromIndex, int toIndex) {
        return list.subList(fromIndex, toIndex);
    }

    @Override
    public boolean equals(Object o) {
        return list.equals(o);
    }

    @Override
    public int hashCode() {
        return list.hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + list + '}';
    }
}
